# Header

menu:
  主页: /
  随笔: /essay/随笔文章目录.html
  仓库: /respositories/仓库目录.html
  档案: /archives
  #相册: /photos

# SubNav
subnav:
  github: "https://github.com/Hermesfuxi"
  weibo: "https://weibo.com/2515902731/profile?topnav=1&wvr=6&is_all=1"
  #rss: "#"
  zhihu: "https://www.zhihu.com/people/tang-guo-xin-24/activities"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  bilibili: "https://space.bilibili.com/301958531"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
fancybox: true
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay:
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: '4cd8f44d6369903c586037ae4c8b0ab1'
google_analytics: 'UA-159656146-1'
favicon: /favicon.png

#你的头像url
avatar: /img/touxiang.png

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友情链接'
#  friends: false
  aboutme: '关于我'

friends:
  NE0的博客: https://ne0matrix.com/
  血饮评论: http://www.dacankao.com/forum-91-1.html

aboutme: <div>
  <div> 闻道易，悟道难。得道易，证道难。</div>
  <br/>
  <div> 悟道不足以得道，得道不足以证道，证道不足以穷道。</div>
  <br/>
  <div> 证道以穷之，于是乎学在矣，于是乎道在矣，于是乎性命在矣。穷理尽性，以至于命。治学即求道，道不悟则学不成。</div>
  <br/>
  <div> 后天之学，迹也。先天之学，心也。迹者形而下为器，心者形而上为道，道器不二，心迹同一。</div>
  <br/>
  <div> 鄙人不才，受先人感召，矢志于道，愿遍研一切重大文明之根本见地，综核名实，权衡偏正，叹大褒圆，中道立极，皇极经世。</div>
  <br/>
  <div> 所谓皇极者，其大中也欤！不立皇极，何以经世？不依中道，何以立极？不遍察各大文明一切圣贤教诲，何以行中庸之道？</div>
  <br/>
  <div> 为天地立心，为生民立命，为往圣继绝学，为万世开太平。我辈证道修真，当发挥往圣先贤于穆不巳、自强不息、周流不殆之精神，海纳百川，不择细流，自宰无量而终成巨浸。群经皆为我注脚，万法皆为我所用，如是方为达道。</div>
  <div>

#gitalk评论
gitalk:
  enable:  true
  githubID:  Hermesfuxi
  admin:  Hermesfuxi
  owner:  Hermesfuxi
  repo: Hermesfuxi.github.io
  clientID:  69a353d27e4def5e94db
  clientSecret:  b1935f42e0ff6190c38799bd0944182d8cf3e1ed
  #不这样书写容易报错
  adminUser:  Hermesfuxi
  labels: gitalk
  perPage: 15
  pagerDirection: last
  createIssueManually: true
  distractionFreeMode: true

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: ture
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
